import 'dart:io';
import 'dart:typed_data';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:pretty_qr_code/pretty_qr_code.dart';
import 'package:screenshot/screenshot.dart';
import 'package:share_plus/share_plus.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:path_provider/path_provider.dart';
import 'package:open_file/open_file.dart';
import '../../models/history_item.dart';
import '../../services/history_service.dart';

const Color primaryColor = Color(0xFF3A2EC3);

const List<Color> qrColors = [
  Colors.white,
  Colors.grey,
  Colors.orange,
  Colors.yellow,
  Colors.green,
  Colors.cyan,
  Colors.purple,
];

class QrGeneratorScreen extends StatefulWidget {
  const QrGeneratorScreen({super.key});

  @override
  State<QrGeneratorScreen> createState() => _QrGeneratorScreenState();
}

class _QrGeneratorScreenState extends State<QrGeneratorScreen> {
  final ScreenshotController _screenshotController = ScreenshotController();
  OverlayEntry? _overlayEntry;
  final ValueNotifier<List<ToastData>> _toastQueue = ValueNotifier([]);

  // Form State
  String? _qrData;
  Color _qrColor = Colors.white;
  bool _hasReceivedInitialData = false;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    if (!_hasReceivedInitialData) {
      final args = ModalRoute.of(context)?.settings.arguments;
      if (args is String && args.isNotEmpty) {
        setState(() {
          _qrData = args;
        });
      }
      _hasReceivedInitialData = true;
    }
  }

  @override
  void dispose() {
    _overlayEntry?.remove();
    _overlayEntry = null;
    super.dispose();
  }

  // --- PDF GENERATION ---
  Future<void> _generateAndPrintPdf() async {
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (context) => const Center(child: CircularProgressIndicator()),
    );

    try {
      await Future.delayed(const Duration(milliseconds: 100));

      final imageBytes = await _screenshotController.capture(
          pixelRatio: MediaQuery.of(context).devicePixelRatio);

      if (imageBytes == null) {
        if (mounted) Navigator.pop(context);
        return;
      }

      final pdf = pw.Document();
      final qrImage = pw.MemoryImage(imageBytes);

      pdf.addPage(
        pw.Page(
          pageFormat: PdfPageFormat.a4,
          build: (pw.Context context) {
            return pw.Stack(
              children: [
                pw.Center(
                  child: pw.Opacity(
                    opacity: 0.1,
                    child: pw.Text(
                      'QR S&G',
                      style: pw.TextStyle(
                        fontSize: 80,
                        fontWeight: pw.FontWeight.bold,
                        fontStyle: pw.FontStyle.italic,
                      ),
                    ),
                  ),
                ),
                pw.Center(
                  child: pw.Column(
                    mainAxisAlignment: pw.MainAxisAlignment.center,
                    children: [
                      pw.Text('QR Code Result',
                          style: pw.TextStyle(
                              fontSize: 24, fontWeight: pw.FontWeight.bold)),
                      pw.SizedBox(height: 30),
                      pw.Container(
                        padding: const pw.EdgeInsets.all(20),
                        decoration: pw.BoxDecoration(
                          border: pw.Border.all(width: 2),
                          borderRadius: pw.BorderRadius.circular(10),
                        ),
                        child: pw.Image(qrImage, width: 250, height: 250),
                      ),
                      pw.SizedBox(height: 30),
                      pw.Text('Data:',
                          style: pw.TextStyle(
                              fontSize: 16, color: PdfColors.grey700)),
                      pw.SizedBox(height: 5),
                      pw.Text(_qrData ?? '-',
                          style: pw.TextStyle(
                              fontSize: 18, fontWeight: pw.FontWeight.bold)),
                      pw.Spacer(),
                      pw.Text('Generated by QR S&G App',
                          style: pw.TextStyle(
                              fontSize: 12, color: PdfColors.grey)),
                    ],
                  ),
                ),
              ],
            );
          },
        ),
      );

      if (!kIsWeb) {
        String? path;
        try {
          if (Platform.isAndroid) {
            path =
                '/storage/emulated/0/Download/QR_${DateTime.now().millisecondsSinceEpoch}.pdf';
          } else {
            final dir = await getDownloadsDirectory();
            if (dir != null) {
              path =
                  '${dir.path}/QR_${DateTime.now().millisecondsSinceEpoch}.pdf';
            }
          }

          if (path != null) {
            final file = File(path);
            await file.writeAsBytes(await pdf.save());

            // History
            await HistoryService().addToHistory(HistoryItem(
              id: DateTime.now().toString(),
              type: HistoryType.create,
              data: _qrData!,
              timestamp: DateTime.now(),
            ));

            if (mounted) Navigator.pop(context);

            if (mounted) {
              ScaffoldMessenger.of(context).showSnackBar(
                SnackBar(
                  content: Text('PDF Saved: $path'),
                  backgroundColor: Colors.green,
                  action: SnackBarAction(
                    label: 'OPEN',
                    textColor: Colors.white,
                    onPressed: () => OpenFile.open(path),
                  ),
                ),
              );
            }
            await OpenFile.open(path);
            return;
          }
        } catch (e) {
          debugPrint('Failed to save file: $e');
        }
      }

      if (mounted) Navigator.pop(context);
      await Printing.layoutPdf(
        onLayout: (format) async => pdf.save(),
        name: 'QR_Code_${DateTime.now().millisecondsSinceEpoch}.pdf',
      );
    } catch (e) {
      if (mounted) Navigator.pop(context);
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Error: $e'), backgroundColor: Colors.red),
      );
    }
  }

  // --- PNG SAVING ---
  Future<void> _savePng() async {
    if (_qrData == null || _qrData!.isEmpty) {
      _showErrorSnackBar(context);
      return;
    }

    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (context) => const Center(child: CircularProgressIndicator()),
    );

    try {
      await Future.delayed(const Duration(milliseconds: 100));
      final imageBytes = await _screenshotController.capture(pixelRatio: 3.0);

      if (imageBytes == null) {
        if (mounted) Navigator.pop(context);
        return;
      }

      if (kIsWeb) {
        if (mounted) {
          Navigator.pop(context);
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
                content: Text('Use Share feature for Web download.'),
                backgroundColor: Colors.orange),
          );
        }
        return;
      }

      String? path;
      if (Platform.isAndroid) {
        path =
            '/storage/emulated/0/Download/QR_${DateTime.now().millisecondsSinceEpoch}.png';
      } else {
        final dir = await getDownloadsDirectory();
        if (dir != null) {
          path = '${dir.path}/QR_${DateTime.now().millisecondsSinceEpoch}.png';
        }
      }

      if (path != null) {
        final file = File(path);
        await file.writeAsBytes(imageBytes);

        // History
        await HistoryService().addToHistory(HistoryItem(
          id: DateTime.now().toString(),
          type: HistoryType.create,
          data: _qrData!,
          timestamp: DateTime.now(),
        ));

        if (mounted) Navigator.pop(context);

        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text('PNG Saved: $path'),
              backgroundColor: Colors.green,
              action: SnackBarAction(
                label: 'OPEN',
                textColor: Colors.white,
                onPressed: () => OpenFile.open(path),
              ),
            ),
          );
        }
        await OpenFile.open(path);
      } else {
        if (mounted) Navigator.pop(context);
      }
    } catch (e) {
      if (mounted) Navigator.pop(context);
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(content: Text('Error: $e'), backgroundColor: Colors.red));
      }
    }
  }

  // --- ERROR SNACKBAR ---
  void _showErrorSnackBar(BuildContext context) {
    if (_overlayEntry == null) {
      _overlayEntry = OverlayEntry(builder: (context) {
        return Positioned(
          top: MediaQuery.of(context).padding.top + 10,
          right: 20,
          width: MediaQuery.of(context).size.width * 0.5,
          child: Material(
            color: Colors.transparent,
            child: ValueListenableBuilder<List<ToastData>>(
              valueListenable: _toastQueue,
              builder: (context, toasts, child) {
                return Column(
                  crossAxisAlignment: CrossAxisAlignment.end,
                  mainAxisSize: MainAxisSize.min,
                  children: toasts.map((t) => ToastWidget(
                        key: ValueKey(t.id),
                        data: t,
                        onDismiss: () {
                          final list = List<ToastData>.from(_toastQueue.value);
                          list.removeWhere((item) => item.id == t.id);
                          _toastQueue.value = list;
                        },
                      )).toList(),
                );
              },
            ),
          ),
        );
      });
      Overlay.of(context).insert(_overlayEntry!);
    }

    final list = List<ToastData>.from(_toastQueue.value);
    if (list.length >= 3) {
      list.removeAt(0);
    }
    list.add(ToastData('Oops! Konten kosong.\nIsi dulu yuk!'));
    _toastQueue.value = list;
  }

  // --- UI START ---
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFF8F9FA),
      appBar: AppBar(
        title: const Text(
          'QR Creator',
          style: TextStyle(
            fontFamily: 'Manrope',
            fontWeight: FontWeight.w700,
            color: Colors.black87,
            fontSize: 20,
          ),
        ),
        backgroundColor: Colors.transparent,
        elevation: 0,
        centerTitle: true,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back_ios_new, color: Colors.black87),
          onPressed: () => Navigator.pop(context),
        ),
      ),
      body: SingleChildScrollView(
        physics: const BouncingScrollPhysics(),
        padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12),
        child: Column(
          children: [
            // HERO CARD SECTION
            Center(
              child: Container(
                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.circular(32),
                  boxShadow: [
                    BoxShadow(
                      color: primaryColor.withOpacity(0.15),
                      blurRadius: 40,
                      offset: const Offset(0, 16),
                    ),
                  ],
                ),
                padding: const EdgeInsets.all(24),
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Screenshot(
                      controller: _screenshotController,
                      child: Container(
                        padding: const EdgeInsets.all(16),
                        decoration: BoxDecoration(
                          color: _qrColor,
                          borderRadius: BorderRadius.circular(20),
                          border: Border.all(
                            color: Colors.grey.shade200,
                            width: 1.5,
                          ),
                        ),
                        child: _qrData == null || _qrData!.isEmpty
                            ? Container(
                                width: 220,
                                height: 220,
                                decoration: BoxDecoration(
                                    color: Colors.grey.shade50,
                                    borderRadius: BorderRadius.circular(16)),
                                child: Column(
                                  mainAxisAlignment: MainAxisAlignment.center,
                                  children: [
                                    Icon(Icons.qr_code_2_rounded,
                                        size: 64, color: Colors.grey.shade300),
                                    const SizedBox(height: 16),
                                    const Text(
                                      'Preview QR',
                                      style: TextStyle(
                                        color: Colors.grey,
                                        fontWeight: FontWeight.w600,
                                      ),
                                    ),
                                  ],
                                ),
                              )
                            : SizedBox(
                                width: 220,
                                height: 220,
                                child: PrettyQrView.data(
                                  data: _qrData!,
                                  decoration: const PrettyQrDecoration(
                                    shape: PrettyQrSmoothSymbol(),
                                  ),
                                ),
                              ),
                      ),
                    ),
                  ],
                ),
              ),
            ),
            const SizedBox(height: 40),

            // INPUT SECTION
            Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Padding(
                  padding: EdgeInsets.only(left: 8, bottom: 8),
                  child: Text(
                    'Content',
                    style: TextStyle(
                      fontWeight: FontWeight.bold,
                      fontSize: 16,
                      color: Colors.black87,
                    ),
                  ),
                ),
                TextField(
                  maxLines: null,
                  decoration: InputDecoration(
                    hintText: 'Enter text or URL here...',
                    hintStyle: TextStyle(color: Colors.grey.shade400),
                    filled: true,
                    fillColor: Colors.white,
                    contentPadding: const EdgeInsets.all(20),
                    border: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(20),
                      borderSide: BorderSide.none,
                    ),
                    enabledBorder: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(20),
                      borderSide: BorderSide.none,
                    ),
                    focusedBorder: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(20),
                      borderSide:
                          const BorderSide(color: primaryColor, width: 2),
                    ),
                    prefixIcon:
                        const Icon(Icons.link_rounded, color: Colors.grey),
                  ),
                  onChanged: (value) {
                    setState(() =>
                        _qrData = value.trim().isEmpty ? null : value.trim());
                  },
                ),
              ],
            ),
            const SizedBox(height: 32),

            // COLOR PICKER
            Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Padding(
                  padding: EdgeInsets.only(left: 8, bottom: 12),
                  child: Text(
                    'Background Color',
                    style: TextStyle(
                      fontWeight: FontWeight.bold,
                      fontSize: 16,
                      color: Colors.black87,
                    ),
                  ),
                ),
                SizedBox(
                  height: 60,
                  child: ListView.separated(
                    scrollDirection: Axis.horizontal,
                    itemCount: qrColors.length,
                    separatorBuilder: (c, i) => const SizedBox(width: 12),
                    itemBuilder: (context, index) {
                      final color = qrColors[index];
                      final isSelected = _qrColor == color;
                      return GestureDetector(
                        onTap: () => setState(() => _qrColor = color),
                        child: HoverWidget(
                          child: AnimatedContainer(
                            duration: const Duration(milliseconds: 200),
                            width: 50,
                            height: 50,
                            decoration: BoxDecoration(
                              color: color,
                              shape: BoxShape.circle,
                              border: Border.all(
                                color: isSelected
                                    ? primaryColor
                                    : Colors.grey.shade200,
                                width: isSelected ? 3 : 1,
                              ),
                              boxShadow: isSelected
                                  ? [
                                      BoxShadow(
                                        color: color.withOpacity(0.4),
                                        blurRadius: 10,
                                        offset: const Offset(0, 4),
                                      )
                                    ]
                                  : [],
                            ),
                            child: isSelected && color == Colors.white
                                ? const Center(
                                    child: Icon(Icons.check,
                                        size: 20, color: primaryColor))
                                : (isSelected
                                    ? const Center(
                                        child: Icon(Icons.check,
                                            size: 20, color: Colors.white))
                                    : null),
                          ),
                        ),
                      );
                    },
                  ),
                ),
              ],
            ),
            const SizedBox(height: 48),

            // ACTION BUTTONS
            Row(
              children: [
                Expanded(
                  child: _buildActionButton(
                    icon: Icons.share_rounded,
                    label: 'Share',
                    color: const Color(0xFF4B68FF),
                    onTap: () async {
                      if (_qrData == null || _qrData!.isEmpty) {
                        _showErrorSnackBar(context);
                        return;
                      }
                      await Future.delayed(const Duration(milliseconds: 100));
                      final imageBytes = await _screenshotController.capture(
                          pixelRatio: MediaQuery.of(context).devicePixelRatio);
                      if (imageBytes != null) {
                        await Share.shareXFiles([
                          XFile.fromData(imageBytes,
                              name:
                                  'qr_pro_${DateTime.now().millisecondsSinceEpoch}.png',
                              mimeType: 'image/png')
                        ]);
                        // History
                        await HistoryService().addToHistory(HistoryItem(
                          id: DateTime.now().toString(),
                          type: HistoryType.create,
                          data: _qrData!,
                          timestamp: DateTime.now(),
                        ));
                      }
                    },
                  ),
                ),
                const SizedBox(width: 16),
                Expanded(
                  child: _buildActionButton(
                    icon: Icons.send_rounded,
                    label: 'Send',
                    color: const Color(0xFF00C853),
                    isEnabled: _qrData != null && _qrData!.isNotEmpty,
                    onTap: () async {
                      // Send Logic
                      await Future.delayed(const Duration(milliseconds: 100));
                      final imageBytes = await _screenshotController.capture(
                          pixelRatio: MediaQuery.of(context).devicePixelRatio);
                      if (imageBytes != null) {
                        await Share.shareXFiles(
                          [
                            XFile.fromData(imageBytes,
                                name: 'qr_pro.png', mimeType: 'image/png')
                          ],
                          text:
                              'Here is your Premium QR Code for: ${_qrData ?? ''}',
                        );
                        // History
                        await HistoryService().addToHistory(HistoryItem(
                          id: DateTime.now().toString(),
                          type: HistoryType.create,
                          data: _qrData!,
                          timestamp: DateTime.now(),
                        ));
                      }
                    },
                  ),
                ),
                const SizedBox(width: 16),
                Expanded(
                  child: _buildActionButton(
                    icon: Icons.print_rounded,
                    label: 'Print',
                    color: const Color(0xFF9C27B0),
                    isEnabled: _qrData != null && _qrData!.isNotEmpty,
                    onTap: _generateAndPrintPdf,
                  ),
                ),
              ],
            ),
            const SizedBox(height: 24),

            // RESET BUTTON
            TextButton.icon(
              onPressed: () {
                setState(() {
                  _qrData = null;
                  _qrColor = Colors.white;
                });
              },
              icon: const Icon(Icons.refresh_rounded, color: Colors.redAccent),
              label: const Text(
                'Reset All',
                style: TextStyle(
                    color: Colors.redAccent,
                    fontWeight: FontWeight.w600,
                    fontSize: 16),
              ),
              style: TextButton.styleFrom(
                padding:
                    const EdgeInsets.symmetric(horizontal: 24, vertical: 12),
                shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(30)),
              ),
            ),
            const SizedBox(height: 40),
          ],
        ),
      ),
    );
  }

  Widget _buildActionButton({
    required IconData icon,
    required String label,
    required Color color,
    VoidCallback? onTap,
    bool isEnabled = true,
  }) {
    return HoverWidget(
      hoverScale: 1.05,
      child: Container(
        decoration: BoxDecoration(
          boxShadow: isEnabled
              ? [
                  BoxShadow(
                    color: color.withOpacity(0.3),
                    blurRadius: 12,
                    offset: const Offset(0, 6),
                  )
                ]
              : [],
        ),
        child: ElevatedButton(
          onPressed: isEnabled ? onTap : null,
          style: ElevatedButton.styleFrom(
            backgroundColor: color,
            disabledBackgroundColor: Colors.grey.shade300,
            foregroundColor: Colors.white,
            disabledForegroundColor: Colors.grey.shade500,
            padding: const EdgeInsets.symmetric(vertical: 16),
            shape:
                RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
            elevation: 0,
          ),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Icon(icon, size: 22),
              const SizedBox(height: 4),
              Text(label,
                  style: const TextStyle(
                      fontWeight: FontWeight.w600, fontSize: 12)),
            ],
          ),
        ),
      ),
    );
  }
}

class ToastData {
  final String id;
  final String message;
  ToastData(this.message)
      : id = DateTime.now().toString() + (UserIndex++).toString();
  static int UserIndex = 0;
}

class ToastWidget extends StatefulWidget {
  final ToastData data;
  final VoidCallback onDismiss;
  const ToastWidget({super.key, required this.data, required this.onDismiss});

  @override
  State<ToastWidget> createState() => _ToastWidgetState();
}

class _ToastWidgetState extends State<ToastWidget> {
  double _opacity = 0.0;

  @override
  void initState() {
    super.initState();
    Future.microtask(() {
      if (mounted) setState(() => _opacity = 1.0);
    });
    Future.delayed(const Duration(milliseconds: 1500), () {
      if (mounted) setState(() => _opacity = 0.0);
    });
  }

  @override
  Widget build(BuildContext context) {
    return AnimatedOpacity(
      opacity: _opacity,
      duration: const Duration(milliseconds: 500),
      onEnd: () {
        if (_opacity == 0.0) widget.onDismiss();
      },
      child: Container(
        width: double.infinity,
        margin: const EdgeInsets.only(bottom: 12),
        padding: const EdgeInsets.all(12),
        decoration: BoxDecoration(
          color: Colors.red.shade600,
          borderRadius: BorderRadius.circular(12),
          boxShadow: [
            BoxShadow(
                color: Colors.black.withOpacity(0.15),
                blurRadius: 8,
                offset: const Offset(0, 4))
          ],
        ),
        child: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            const Icon(Icons.warning_amber_rounded,
                color: Colors.white, size: 20),
            const SizedBox(width: 8),
            Expanded(
              child: Text(
                widget.data.message,
                style: const TextStyle(
                  color: Colors.white,
                  fontWeight: FontWeight.bold,
                  fontSize: 12,
                  fontFamily: 'Manrope',
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class HoverWidget extends StatefulWidget {
  final Widget child;
  final double hoverScale;

  const HoverWidget({super.key, required this.child, this.hoverScale = 1.1});

  @override
  State<HoverWidget> createState() => _HoverWidgetState();
}

class _HoverWidgetState extends State<HoverWidget>
    with SingleTickerProviderStateMixin {
  late AnimationController _controller;
  late Animation<double> _scaleAnimation;

  @override
  void initState() {
    super.initState();
    _controller = AnimationController(
        vsync: this, duration: const Duration(milliseconds: 200));
    _scaleAnimation = Tween<double>(begin: 1.0, end: widget.hoverScale).animate(
      CurvedAnimation(parent: _controller, curve: Curves.easeOutCubic),
    );
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MouseRegion(
      onEnter: (_) => _controller.forward(),
      onExit: (_) => _controller.reverse(),
      child: AnimatedBuilder(
        animation: _controller,
        builder: (context, child) => Transform.scale(
          scale: _scaleAnimation.value,
          child: child,
        ),
        child: widget.child,
      ),
    );
  }
}
